### PR TITLE
Fixes for PHP 8.1

### LINKED ISSUE #93: sha1() error when running Behat tests with PHP 8.1
When - for example - running this core test admin/tool/uploadcourse/tests/behat/create.feature the following error is thrown when running tool_ally in a vanilla MOODLE_403_STABLE with PHP 8.1:

```
001 Scenario: Validation of role for uploaded courses # /var/www/html/admin/tool/uploadcourse/tests/behat/create.feature:110
      When I click on "Upload courses" "button"       # /var/www/html/admin/tool/uploadcourse/tests/behat/create.feature:124
        debugging() message/s found:
        Exception encountered in event observer '\tool_ally\event_handlers::course_created': Unknown error type: sha1(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/admin/tool/ally/classes/models/component_content.php on line 67
```

### PR DESCRIPTION
**Pull request by opitz**
As PHP is more strict about types the code needs a bit polishing.
This will fix #93.

### CODE REVIEW

File: classes/files_iterator.php [hunk 1]
```diff
@@ -165,11 +165,11 @@ private function extract_context($row) {
     /**
      * @return \stored_file
      */
-    public function current() {
+    public function current(): mixed {
```
Comment (gthomas2) [inline classes/files_iterator.php:168]: The problem is that it will break things for anyone on < php8.0

Comment (gthomas2) [reply classes/files_iterator.php:168]: Also, type hinting doesn't fix anything for PHP 8.1 - it's still optional in PHP8.1

File: classes/models/component_content.php [hunk 2]
```diff
@@ -64,7 +64,7 @@ public function __construct($id, $component, $table, $field, $courseid, $timemod
                                 $title = null, $url = null) {
         parent::__construct($id, $component, $table, $field, $courseid, $timemodified, $contentformat, $title);
         $this->content = $content;
-        $this->contenthash = sha1($this->content);
+        $this->contenthash = is_string($this->content) ? sha1($this->content) : '';
```
Comment (gthomas2) [inline classes/models/component_content.php:67]: Have you noticed content not being a string at any point? Is this the fix?

File: classes/files_iterator.php (hunk 1 above)
Comment (opitz) [reply classes/files_iterator.php:168]: @gthomas2 Since Moodle 4.2 PHP 8.0 is the minimum requirement. I suggest to create a separate branch for MOODLE_402_STABLE (and/or MOODLE_403_STABLE).

Without type hinting in PHP 8.1 you will see failing in Behat tests (e.g. filter/ally/tests/behat/filter.feature) like this:
`When I reload the page: PHP errors found:
Unknown error type: During inheritance of Iterator: Uncaught Exception: Unknown error type: Return type of tool_ally\files_iterator::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/admin/tool/ally/classes/files_iterator.php on line 168 in /var/www/html/lib/behat/lib.php:157
`

File: classes/models/component_content.php (hunk 2 above)
Comment (opitz) [reply classes/models/component_content.php:67]: You will see failing (core) Behat tests (e.g. admin/tool/uploadcourse/tests/behat/create.future) with PHP 8.1 like this:
`When I click on "Upload courses" "button": debugging() message/s found:
Exception encountered in event observer '\tool_ally\event_handlers::course_created': Unknown error type: sha1(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/admin/tool/ally/classes/models/component_content.php on line 67
`

File: classes/files_iterator.php (hunk 1 above)
Comment (gthomas2) [reply classes/files_iterator.php:168]: Sorry, you are correct here. We actually have a PR open for Moodle 4.2 but we used an annotation to fix the errors: https://github.com/anthology-ally/moodle-tool_ally/pull/91/files#diff-56d533e97b1881bb6228b9b1ca3266c2bb79597f9c57d872608e6e04a46c5701

File: classes/models/component_content.php (hunk 2 above)
Comment (gthomas2) [reply classes/models/component_content.php:67]: Sorry for the late reply. Since the older PR got merged there will be conflicts with this PR - could you rebase, please?

**Comment by opitz** [comment]
Rebased.
Updated PR to reflect your type handling. Now only addressing the string issue.

**Review by gthomas2 — APPROVED** [review]

**Review by mmichalek01 — APPROVED** [review]
